### ISSUE TITLE
Moving tabs causes big explosions

### ISSUE THREAD

**Issue by codingMASTER398** [Birch-san/box2d3-wasm#12]
Probably something to do with deltatime. It's really fun, but probably not the intended behaviour?

https://github.com/user-attachments/assets/b1b5cd84-3842-4390-8b6a-b1fa526d8fce

**Comment by quinton-ashley** [comment]
Yeah haha that's just cause the demo doesn't use a fixed time step.

Perhaps 1/50th should be the max time step amount.

**Comment by ErikSom** [comment]
Fixed in:
https://github.com/Birch-san/box2d3-wasm/commit/89347e3cb1971254bb6e688000bf20ff3408f6c5
