### ISSUE TITLE
Performance hit when JS console is open

### ISSUE THREAD

**Issue by quinton-ashley** [Birch-san/box2d3-wasm#9]
Hi, I thought I'd make a separate issue for this. Can anyone else confirm this issue?

With the console open performance goes down by like 80%, it's crazy.

I'm wondering if this is something that can be fixed or just inherent to Google Chrome when running wasm?

**Comment by codingMASTER398** [comment]
Works fine for me, 100 pyramid height. Brave (Chromium 131.0.6778.139) on Ubuntu 22.04 (Zorin), Wayland. That's a mouthful.
![image](https://github.com/user-attachments/assets/0bb2ee4e-22aa-4442-a4ec-ac6b52e2594f)

**Comment by quinton-ashley** [comment]
Ah yeah it seems to be working fine now for me too!

**Comment by quinton-ashley** [comment]
Going to close this issue. Will reopen if I catch it happening again.

Might have been a temporary Chrome issue that was resolved when I restarted my computer.

**Comment by quinton-ashley** [comment]
This was because I was using the Debug version instead of the Release version. See issue #18 for more info
